blog/urls.py
from django.urls import path

from .views import(
    PostCreateView,
    PostDetailView,
    PostListView,
)

app_name = "blog"

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
]

tags/urls.py
from django.urls import path

from .views import TagListView, TagPostListView

app_name = "tags"

urlpatterns = [
    path('', TagListView.as_view(), name='tag_list'),
    path('<slug:slug>/', TagPostListView.as_view(), name='posts_by_tag'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from model_utils.models import TimeStampedModel

class Post(TimeStampedModel):
    title = models.CharField(max_length=200)
    slug = AutoSlugField("Post Address", always_update=False, populate_from="title")
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    # content = RichTextField(blank=False)
    content = models.TextField(blank=False)

    class Meta:
        ordering = ['-modified']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={"slug": self.slug})

tags/models.py
from django.db import models

from autoslug import AutoSlugField

from blog.models import Post


class Tag(models.Model):
    title = models.CharField(max_length=25)
    slug = AutoSlugField("Tag Address", always_update=False, populate_from="title")
    description = models.TextField(blank=True)
    tags = models.ManyToManyField(Post)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
)

from .models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post

    fields = [
        'title',
        'content',
    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'



class PostListView(ListView):
    paginate_by = 5
    model = Post
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'

templates/blog/post_detail.html
{% extends "_base.html" %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

    <div class="container">

        <h2><a href="">{{ post.title }}</a></h2>
        
        <div class="post-author-heading">
            <h6><a href="{% url 'about' %}">{{ post.author }}</a></h6>
            <h6> on {{ post.created }}</h6>
            <!-- If the post has been updated, display the date of the most recent update in red -->
            {% if post.created != post.modified %}
                <h6 class="updated">Updated {{ post.modified }}</h6>
            {% endif %}
        </div>

        <div>
            {% for tag in post.tag_set.all %}
                <span><a class="btn btn-primary" href="{% url 'tags:posts_by_tag' tag.slug %}">{{ tag.title }}</a></span>
            {% endfor %}
        </div>
    
        <hr/>

        <div class="post-content">
            {{ post.content|linebreaks }}
        </div>  
    </div>

{% endblock content %}

templates/blog/post_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock title %}

{% block content %}
    <h1>Create Post</h1>

    <form method="POST" action="{% url 'blog:create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock content %}

templates/blog/post_list.html
{% extends "_base.html" %}

{% block title %}Blog{% endblock title %}

{% block content %}
    
    <div class="container">

        {% if user.is_staff %}
            <h3>Staff Menu</h3>

            <a class="btn btn-success" href="{% url 'blog:create' %}" role="button">
                Create Post
            </a>

            <hr/>
            
        {% endif %}
        
        
        {% for post in post_list %}
            <div>

                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                
                <div class="post-author-heading">
                    <h6><a href="{% url 'about' %}">{{ post.author }}</a></h6>
                    <h6>on {{ post.created }}</h6>

                    <!-- If the post has been updated, display the date of the most recent update in red --> 
                    {% if post.created != post.modified %}
                        <h6 class="updated">Updated {{ post.modified }}</h6>
                    {% endif %}
                </div>
                        
                <div>
                    {% for tag in post.tag_set.all %}
                        <a class="btn btn-primary" href="{% url 'tags:posts_by_tag' tag.slug %}">{{ tag.title }}</a>
                    {% endfor %}
                </div>
                
                <p>{{ post.description|linebreaks }}</p>
            
                <hr/>

            </div>
        {% endfor %}

        <!-- Pagination -->
        <nav class="pagination">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                {% endif %}
                
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                {% endif %}

            </ul>
        </nav>
    </div>


{% endblock content %}