blog/urls.py
from django.urls import path

from .views import(
    PostCreateView,
    PostDetailView,
    PostListView,
)

app_name = "blog"

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # Third party Apps
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local Apps
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sewing/', include('sewing.urls', namespace='sewing')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('contact/', include('contact.urls', namespace='contact')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from .views import ContactFormView, EmailSentView

app_name = 'contact'

urlpatterns = [
    path('', ContactFormView.as_view(), name='send'),
    path('email-sent/', EmailSentView.as_view(), name='email-sent'),
]

sewing/models.py
from django.db import models
from django.utils.html import mark_safe
from django.urls import reverse

from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Product(TimeStampedModel):


    class Category(models.TextChoices):
        UNSPECIFIED = "unspecified", "Unspecified"
        DOG = "dog", "Dog"
        PEOPLE = "people", "People"

    name = models.CharField(max_length=200)
    slug = AutoSlugField("Product Address", always_update=False,
        populate_from='name')
    description = models.TextField(blank=False)
    category = models.CharField("Category", max_length=20,
        choices=Category.choices, default=Category.UNSPECIFIED)

    class Meta:
        ordering = ['-modified']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sewing:detail', kwargs={"slug": self.slug})


class Image(TimeStampedModel):
    name = models.CharField(max_length=100)
    product = models.ForeignKey(Product, 
        on_delete=models.CASCADE, related_name="images")
    slug = AutoSlugField("Image Address",
        always_update=False, populate_from='name')
    url = models.ImageField(upload_to='sewing/')

    def __str__(self):
        return self.name

    @property
    def thumbnail_preview(self):
        if self.url:
            return mark_safe('<img src="{}"  width="auto" height="200" />'.format(self.url.url))
        return ""

templates/_base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Owen Wholley{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- CSS -->
        <!-- Custom -->
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>

    <body>

        <div class="">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <a class="navbar-brand" href="{% url 'home' %}">Owen Wholley</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:list' %}">Words</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sewing:list' %}">Sewing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact:send' %}">Contact</a>
                        </li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <span>
                        <ul class="navbar-nav mr-auto">
                            {% if request.user.is_authenticated %}
                                <span class="navbar-text">
                                    Hello {{ request.user.username }}! 
                                </span>
                                <li class="nav-item">
                                    <!-- URL provided by django-allauth -->
                                    <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                                </li>
                            {% endif %}
                        </ul>
                    </span>
                </div>

            </nav>
        </div>

        {% comment %} <header>
            <!-- Fixed Navbar -->
            <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
                <a href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">Owen Wholley</a>
                <nav class="my-2 my-md-0 mr-md-3">
                    <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
                    <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
                    <a class="p-2 text-dark" href="{% url 'blog:list' %}">Blog</a>
                    <a class="p-2 text-dark" href="{% url 'sewing:list' %}">Sewing</a>
                    {% if user.is_authenticated %}
                        <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
                    {% else %}
                        <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
                        <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
                    {% endif %}
                </nav>
            </div>
        </header> {% endcomment %}

        <div class="container-fluid">
            {% block content %}

            {% endblock content %}
            
            <div class="footer justify-content-center">
                <h3>&copy 2022 <a href="{% url 'contact:send' %}">Owen Wholley</a></h3>
            </div>
            
        </div>
        
        <!-- JavaScript -->
        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>

        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-1RZ3WHGG5Z"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-1RZ3WHGG5Z');
        </script>
    </body>
</html>

templates/about.html
{% extends "_base.html" %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
    <div class="container">

        <div class="row pt-2 justify-content-center">
            <h1>About Me</h1>
        </div>
        <div class="row py-2">
            <div class="col-sm">
                <img class="img-fluid rounded" src="{% static 'images/owen_sophie_web.jpg' %}" alt="Owen & Sophie">
            </div>

            <div class="col-sm">

                <div class="flex-row double-space pt-2">
                    &emsp;I am a ski industry profesional with varied experience in the manufacturing, retail, and resort sectors. I have spent time
                    on the factory lines for both soft-goods and hard-goods. I have also started my own manufacturing business producing 
                    sewn goods. During my time working with soft-goods, specifically outdoor techincal apparel, I taught myself the basics of sewing.
                    Well, with a little help from my mother and the designer at work... I was able to mix-in my interest in computers building not only
                    this website, but some software to help manage production, by way of tracking inventory and work in progress. One thing led to another
                    and a fun little side project quickly became a serious attempt at starting a business.  
                </div>
                <div class="flex-row double-space">
                    &emsp;Despite working in the 'ski' industry, I am in fact, a knuckle dragging snowboarder. I learned how to snowboard as a very young kid,
                    and have been falling downhill ever since. I've made skis & snowboards, sold skis & snowboards, taught people how to snowboard, and even
                    started working with ski patrol...<i>gasp</i>.
                </div>
            </div>
        </div>

        <div class="row pt-2">

            <div class="col-sm">

                <div class="flex-row double-space">
                    <h5>Certifications</h5>
                    <ul>
                        <li>Wilderness First Responder</li>
                        <li>AIARE Level 1 Avalanche</li>                        
                    </ul>
                </div>

                <div class="flex-row double-space">
                    <h5>Education</h5>
                    <ul>
                        <li>Bachelor's of Science, Mathematics, University of Massachusets, Amherst 2018</li>
                    </ul>
                </div>

                <div class="flex-row double-space">
                    <h5>Computer Skills</h5>
                    <ul>
                        <li>Operating Systems: Windows, MacOS, Linux Desktop & Server</li>
                        <li>Web Development: Django, Postgres, Gunicorn, Nginx</li>
                        <li>Programming Languages: Python</li>
                        <li>Development: Git, Docker</li>
                        <li>IT: Email Administration</li>

                    </ul>
                </div>

            </div>

        </div>
    </div>

{% endblock content %}

templates/home.html
{% extends "_base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
    
    <div class="container-fluid">    
        <!-- <div class="row banner">
                <div class="banner-image">
                    <h2>Owen Wholley Mfg.</h2>
                </div>
        </div> -->
        <div class="row justify-content-center align-items-center">
            <img class="img-fluid banner-image" src="{% static 'images/dab-lab3.jpg' %}" alt="Dab Lab picture"> 
            
        </div>
        
        <div class="container">
            
            <div class="row px-2">
                <h1>Events</h1>
            </div>

            <div class="row">
                <div class="col-sm-4 text-center text-justify">
                    <h4><a href="https://www.facebook.com/HarrisonCommunityDay">Harrison Community Fair</a></h4>
                    <h6>Saturday, July 9th 2022</h6>
                    <h6>Harrison, ME</h6>
                    <!-- <p>'An old fashioned community fair where neighbors, families and friends can get together and have fun! There will be a 5k race, food trucks, crafts & vendors, contests, music, games, duck race and so much more!'</p> -->
                </div>
                <div class="col-sm-4">
                    <img class="img-thumbnail fair-thumbnail mx-auto d-block" src="{% static 'images/harrison-community-fair.jpg' %}" alt="Harrison Community Fair">
                </div>
                <div class="col-sm-4 text-center">
                    <p>'An old fashioned community fair where neighbors, families and friends can get together and have fun! There will be a 5k race, food trucks, crafts & vendors, contests, music, games, duck race and so much more!'</p>
                </div>
            </div>
            
            <hr/>

            <div class="row px-2">
                <h1>Products</h1>
            </div>
            
            <div class="row product-row">
                {% for product in product_list %}
                    <div class="col-sm-4 product-col">
                        <a href="{% url 'sewing:detail' product.slug %}">
                            <img class="img-fluid rounded" style="height:200px;" src="{{product.images.first.url.url }}" alt="{{ product.imgaes.first.name }}">
                            <h2>{{ product.name }}</h2>
                        </a>
                    </div> 
                {% endfor %}
            </div>
                
            <div class="row ml-2">
                <a class="btn btn-primary" href="{% url 'sewing:list'  %}" role="button">See More</a>
            </div>
            
        </div>
        
        
    </div>
    
{% endblock content %}

<!-- <div class="row min-vh-100 justify-content-center align-items-center"></div> -->